language: python
python:
  - "3.6"
install:
  - sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
  - pip install -r requirements.txt
script:
  - make doctest
  - make html
  - make latexpdf
