dist: xenial
language: python
python:
  - "3.6"
install:
  - sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk librsvg2-bin plantuml
  # plantuml is really outdated, smuggle in the latest upstream
  - sudo wget -O /usr/share/plantuml/plantuml.jar http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
  - pip install -r requirements.txt
  - pip install -e .
script:
  - make doctest
  - make html
  - make latexpdf
